### ISSUE TITLE
Diseñar A*

### ISSUE THREAD

**Issue by randsec** [Kaerit/JasonIsoMonks#1]
Diseñar algoritmo A\* para el movimiento de monjes.

Determinados tipos de obstáculos serán otros monjes con los que el monje principal podrá interactuar.

**Comment by hecmartinsol** [comment]
'Estamos trabajando en ello' como dijo Aznar

**Comment by randsec** [comment]
Commit: https://github.com/Kaerit/JasonIsoMonks/commit/d5d769e0a1ef819282f6b2a4722763072ac498e6
